#!/bin/sh

# wallpaper
feh --bg-scale ~/Pictures/Wallpapers/wallhaven-5729x8.jpg

# launch polybar
/home/dan/.config/polybar/launch.sh

# launch greenclip
greenclip daemon &


# bspwm config
pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d 1 2 3 4 5 6 7 8 9 0

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Emacs state=tiled
bspc rule -a Screenkey manage=off

# bspc rule -a Gimp desktop='^8' state=floating follow=on
# bspc rule -a Chromium desktop='^2'
# bspc rule -a mplayer2 state=floating
# bspc rule -a Kupfer.py focus=on
